### ISSUE TITLE
Use from file system?

### ISSUE THREAD

**Issue by ComLock** [tineikt/xp-lib-freemarker#2]
I tried using it from file system by adding this to build.gradle dependencies:
runtime files('../../tineikt/xp-lib-freemarker/build/libs/xp-lib-freemarker-0.1.8.jar')

And then i do:
import { render as freemarker    } from '/lib/xp/freemarker';

Which gets transpiled into:
var _freemarker = require('/lib/xp/freemarker');

And I end up with this:
java.lang.ClassNotFoundException: no.tine.xp.lib.freemarker.FreemarkerService not found

**Comment by ComLock** [comment]
What was the url to the "nexus" where I can use the file directly from the net?

Perhaps example syntax for build.gradle?

**Comment by nitelite** [comment]
The most straight forward way to get it going is probably jitpack, which makes a public github repo available as a gradle dependency:

Add it in your root build.gradle at the end of repositories:
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
Step 2. Add the dependency

dependencies {
        include 'com.github.tineikt:xp-lib-freemarker:0.9'
}

**Comment by ComLock** [comment]
https://jitpack.io/#tineikt/xp-lib-freemarker

**Comment by ComLock** [comment]
Adding:
maven { url 'https://jitpack.io' }

To the "top-level" repositories (not the buildscripts repositories)

And then adding:
compile 'com.github.tineikt:xp-lib-freemarker:0.9'

To "top-level" dependencies.

Compiles fine, but I still end up with the same error message.

The 0.9 release is from November. Perhaps a newer release could help? :)

**Comment by ComLock** [comment]
Can actually use commits trying this now:
compile 'com.github.tineikt:xp-lib-freemarker:1e208d5517'

**Comment by ComLock** [comment]
Didn't help. Might be something with our build system.

**Comment by ComLock** [comment]
I tried to copy the contents of https://github.com/tineikt/xp-lib-freemarker/blob/master/src/main/resources/site/lib/xp/freemarker.js and paste that into where I use it. But that just gave me:
java.lang.ClassNotFoundException: no.tine.xp.lib.freemarker.FreemarkerService not found by no.posten.postennorge [82] (java.lang.RuntimeException)

So somehow the lib does not get included. Perhaps I must compile and include?

**Comment by nitelite** [comment]
The gradle dependency should be "include", not "compile" for using an external lib in your app :) Did you try that?

**Comment by ComLock** [comment]
I thought I tried that first, and got a compilation error.
Now I tried both compile and include.

The console now says: 

10:07:26.791 INFO  Application [no.posten.postennorge] installed successfully
10:07:26.799 INFO  Configuring freemarker
10:07:59.699 ERROR IO with the script.
freemarker.template.TemplateNotFoundException: Template not found for name "no.posten.postennorge:/site/parts/heading/heading.html.ftl".
The name was interpreted by this TemplateLoader: no.tine.xp.lib.freemarker.ResourceTemplateLoader@81f6f4b.

I will try just include again.

**Comment by ComLock** [comment]
AH

**Comment by ComLock** [comment]
Of course our build system does not include ftl files. ROFL

**Comment by ComLock** [comment]
Yes works now.

Let me try using 0.9 release too.

**Comment by ComLock** [comment]
0.9 works too.
